version: '3'
services:
    rabbitmq:
        image: rabbitmq:3.8.19-management
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            RABBITMQ_DEFAULT_USER: quest
            RABBITMQ_DEFAULT_PASS: quest
